### ISSUE TITLE
Link color

### ISSUE THREAD

**Issue by ghost** [hyphen-reader/hyphen#58]
I can barely see links on some background colors. (light blue)

**Comment by matt-curtis** [comment]
I don't have any plans currently to add this as an option to the Customizations & Formatting section. You can do the same thing, however, using a custom CSS stylesheet placed in the Documents folder:

``` css
// your-reading-stylesheet.css

a { color: yourcolor; }
```
